2018-04-22 20:34:17,114 ERROR: Exception on /user/rachel [GET] [in /Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/andreasantarlasci/Apps/microblog/app/routes.py", line 78, in user
    return render_template('user.html', user=user, posts=posts)
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/andreasantarlasci/Apps/microblog/app/templates/user.html", line 15, in template
    <p><a href="{{ url_for('follow'), username=user.username }}">Follow</a></p>
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 213, in parse_if
    'name:endif'))
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 876, in subparse
    self.stream.expect('variable_end')
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/jinja2/lexer.py", line 384, in expect
    self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got '='
2018-04-22 20:37:23,921 INFO: Microblog startup [in /Users/andreasantarlasci/Apps/microblog/app/__init__.py:41]
2018-04-23 19:29:05,192 INFO: Microblog startup [in /Users/andreasantarlasci/Apps/microblog/app/__init__.py:41]
2018-04-23 19:29:17,415 INFO: Microblog startup [in /Users/andreasantarlasci/Apps/microblog/app/__init__.py:41]
2018-04-23 19:32:07,515 INFO: Microblog startup [in /Users/andreasantarlasci/Apps/microblog/app/__init__.py:41]
2018-04-23 19:32:23,039 INFO: Microblog startup [in /Users/andreasantarlasci/Apps/microblog/app/__init__.py:41]
2018-04-23 19:32:44,825 INFO: Microblog startup [in /Users/andreasantarlasci/Apps/microblog/app/__init__.py:41]
2018-04-23 19:32:57,510 ERROR: Exception on /index [POST] [in /Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/andreasantarlasci/Apps/microblog/app/routes.py", line 23, in index
    post = Post(body=form.body.data, author=current_user)
AttributeError: 'PostForm' object has no attribute 'body'
2018-04-23 19:33:43,702 INFO: Microblog startup [in /Users/andreasantarlasci/Apps/microblog/app/__init__.py:41]
2018-04-23 19:34:40,281 INFO: Microblog startup [in /Users/andreasantarlasci/Apps/microblog/app/__init__.py:41]
2018-04-23 19:43:29,552 INFO: Microblog startup [in /Users/andreasantarlasci/Apps/microblog/app/__init__.py:41]
2018-04-23 19:45:04,199 INFO: Microblog startup [in /Users/andreasantarlasci/Apps/microblog/app/__init__.py:41]
2018-04-23 19:45:24,985 INFO: Microblog startup [in /Users/andreasantarlasci/Apps/microblog/app/__init__.py:41]
2018-04-23 19:52:54,830 INFO: Microblog startup [in /Users/andreasantarlasci/Apps/microblog/app/__init__.py:41]
2018-04-23 19:52:58,808 INFO: Microblog startup [in /Users/andreasantarlasci/Apps/microblog/app/__init__.py:41]
2018-04-23 19:53:03,522 ERROR: Exception on /index [GET] [in /Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/andreasantarlasci/Apps/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/andreasantarlasci/Apps/microblog/app/routes.py", line 30, in index
    page, app.config['POSTS_PER_PAGE'], False).all()
AttributeError: 'Pagination' object has no attribute 'all'
2018-04-23 19:53:22,744 INFO: Microblog startup [in /Users/andreasantarlasci/Apps/microblog/app/__init__.py:41]
2018-04-23 20:08:56,839 INFO: Microblog startup [in /Users/andreasantarlasci/Apps/microblog/app/__init__.py:41]
